### PR TITLE
Add basic functionality

### PR DESCRIPTION
**Pull request by phiros**
This PR adds basic functionality to drone. Some very basic 'plugins' are included which implement a pipeline style workflow. Each plugin registers with a workflow domain and sends a numerical priority and a signal to the workflow manager. If a workflow domain is triggered (for example 'job.new') all plugins are executed in sequence for this domain (the sequence is determined by their priority).

Currently, a drone can (most of this requires strider-cd/core#15):
- Polls core for new jobs
- It can accept either github (received by core via github webhooks) or rest jobs (received via cores rest api)
- If a github job is encountered it can check whether a `.travis.yml` file is present in the repo. If this is the case it can create more jobs according to what is specified in the file (with the cmds included in the file). If there are multiple `ENV` fields defined in the file it submits multiple jobs to core via the rest API (in travis: multiple ENVs === matrix job). Matrix jobs are a good abstraction for concurrent jobs in CI (and CD) systems.
- A simple local runner implementation runs jobs and streams the results to core via primus.
  End results are submitted to core via the rest API.
- There is also a simple command filter included which filters out unwanted commands (currently everything including the command `sudo`)
- Only one job is processed by a drone at any time. If you need to scale: just start more drone processes.

BTW: I am not sure about the workflow yet. Ideally I would like to see something like flow-based programming being used here. Something like http://noflojs.org/documentation/ would be a nice paradigm for the plugin system. It would allow users to 'wire up' plugins to build their own workflow pipelines exactly in the way they need it.

### CODE REVIEW

**Comment by phiros** [comment]
@knownasilya ping

**Comment by knownasilya** [comment]
I want to keep drones more light weight, so no travis support out of the box. I think that should be a plugin.

**Comment by phiros** [comment]
Drone and core are both prototypes and it will take us some time to work out how
they should function in detail. Until then we will probably try some different ideas out and
we will keep some of those. This implies a lot of bigger and smaller code changes.

Since, we haven't figured out how plugins / the workflow should work in detail I'd like to keep those very basic 'plugins' inside this repo. Otherwise we might run in situations where we have to change a lot of code in all plugin repos (probably more than 4 repos) just because we changed something in the plugin API etc. (I think this is something that is very likely to happen). 
This would (IMHO) slow down development quite a bit (at least I fear that it would slow down
myself).

**Comment by knownasilya** [comment]
Good point.

**Pull request merged**
